### ISSUE TITLE
Add stories

### ISSUE THREAD

**Issue by christopherstyles** [christopherstyles/ngp_van#28]
See: https://developers.ngpvan.com/van-api#stories

**Comment by kinsomicrote** [comment]
Hello @christopherstyles 

Is this a WIP and can I contribute by sending a PR in that regards?

**Comment by christopherstyles** [comment]
Sure thing @kinsomicrote, send away! Maybe take a look at #11 for a reference point. Appreciate your willingness to contribute, cheers!

**Comment by christopherstyles** [comment]
Closed by #31.
