### ISSUE TITLE
Incomplete endpoint for people

### ISSUE THREAD

**Issue by kinsomicrote** [christopherstyles/ngp_van#35]
Hello, @christopherstyles, I'm curious, is there a reason why the [`People`](https://developers.ngpvan.com/van-api#people) module does not include the complete list of endpoints available on [NGP Van](https://developers.ngpvan.com/van-api#people)?

Can I go-ahead to include the others? I need a handful of some that were not included for a work project.

Thanks.

**Comment by kinsomicrote** [comment]
Hello @christopherstyles, can I go-ahead to do this for as many as I can?

**Comment by christopherstyles** [comment]
Wow I’m so sorry for not getting back to you until now @kinsomicrote. Been a crazy year! If you’re still interested in filling out missing modules, feel free 😉
