### ISSUE TITLE
Okay to loosen dependency versions?

### ISSUE THREAD

**Issue by woodhull** [christopherstyles/ngp_van#6]
We've loosened the faraday deps to work with the newer version that we are using. 

Is there a reason they needed to be restricted to `0.9`? The specs seems to pass against faraday `0.15`.... but we've not tested extensively. 

https://github.com/controlshift/ngp_van/commit/4c503a3c798568a0dc3698817f7c91209f328770

**Comment by christopherstyles** [comment]
Thanks @woodhull, this has been updated in [v0.1.3](https://github.com/christopherstyles/ngp_van/releases/tag/v0.1.3).
